import { Router } from 'express';
import usersRouter from '@modules/users/routes/users.routes';
import sessionsRouter from '@modules/users/routes/sessions.routes';
import passwordRouter from '@modules/users/routes/password.routes';
import profileRouter from '@modules/users/routes/profile.routes';
import pacientesRouter from '@modules/pacientes/paciente/routes/pacientes.routes';
import agendamentoRouter from '@modules/agendamentos/agendamento/routes/agendamento.routes';
import agendamentoTipoRouter from '@modules/agendamentos/agendamentoTipo/routes/agendamentoTipo.routes';
import atendimentoRouter from '@modules/atendimentos/atendimento/routes/atendimento.routes';
import atendimentoProcedimentoRouter from '@modules/atendimentos/atendimentoProcedimento/routes/atendimentoProcedimento.routes';
import clinicaRouter from '@modules/clinicas/routes/clinica.routes';
import convenioRouter from '@modules/convenios/routes/convenio.routes';
import documentoMedicoRouter from '@modules/documentos/documentoMedico/routes/documentoMedico.routes';
import documentoTipoRouter from '@modules/documentos/documentoTipo/routes/documentoTipo.routes';
import especialidadeRouter from '@modules/especialidades/routes/especialidade.routes';
import medicoRouter from '@modules/medicos/medico/routes/medico.routes';
import medicoClinicaRouter from '@modules/medicos/medicoClinica/routes/medicoClinica.routes';
import medicoEspecialidadeRouter from '@modules/medicos/medicoEspecialidade/routes/medicoEspecialidade.routes';
import pacienteContatoRouter from '@modules/pacientes/pacienteContato/routes/pacienteContato.routes';
import pacienteConvenioRouter from '@modules/pacientes/pacienteConvenio/routes/pacienteConvenio.routes';
import pacienteEnderecoRouter from '@modules/pacientes/pacienteEndereco/routes/pacienteEndereco.routes';
import pacientePatologiaRiscoRouter from '@modules/pacientes/pacientePatologiaRisco/routes/pacientes.routes';
import patologiaRoutes from '@modules/patologias/routes/patologia.routes';
import procedimentoRouter from '@modules/procedimentos/routes/procedimento.routes';
import programaRouter from '@modules/programas/programa/routes/programa.routes';
import programaClinicaRouter from '@modules/programas/programaClinica/routes/programaClinica.routes';
import prontuarioRouter from '@modules/prontuarios/prontuario/routes/prontuario.routes';
import prontuarioExameFisicoRouter from '@modules/prontuarios/prontuarioExameFisico/routes/prontuarioExameFisico.routes';
import prontuarioHabitoVidaRouter from '@modules/prontuarios/prontuarioHabitoVida/routes/prontuarioHabitoVida.routes';
import prontuarioHistoricoSaudeRouter from '@modules/prontuarios/prontuarioHistoricoSaude/routes/prontuarioHistoricoSaude.routes';
import prontuarioQueixaSaudeRouter from '@modules/prontuarios/prontuarioQueixaSaude/routes/prontuarioQueixaSaude.routes';
import riscoRouter from '@modules/riscos/routes/risco.routes';
import solicitacaoRouter from '@modules/solicitacoes/solicitacao/routes/solicitacao.routes';
import solicitacaoItemRouter from '@modules/solicitacoes/solicitacaoItem/routes/solicitacaoItem.routes';
import tipoAgendamentoRouter from '@modules/tipoAgendamento/routes/tipoAgendamento.routes';

const routes = Router();

routes.use('/users', usersRouter);
routes.use('/sessions', sessionsRouter);
routes.use('/password', passwordRouter);
routes.use('/profile', profileRouter);
routes.use('/pacientes', pacientesRouter);
routes.use('/agendamento', agendamentoRouter);
routes.use('/agendamentoTipo', agendamentoTipoRouter);
routes.use('/atendimento', atendimentoRouter);
routes.use('/atendimentoProcedimento', atendimentoProcedimentoRouter);
routes.use('/clinica', clinicaRouter);
routes.use('/convenio', convenioRouter);
routes.use('/documentoMedico', documentoMedicoRouter);
routes.use('/documentoTipo', documentoTipoRouter);
routes.use('/especialidade', especialidadeRouter);
routes.use('/medico', medicoRouter);
routes.use('/medicoClinica', medicoClinicaRouter);
routes.use('/medicoEspecialidade', medicoEspecialidadeRouter);
routes.use('/pacienteContato', pacienteContatoRouter);
routes.use('/pacienteConvenio', pacienteConvenioRouter);
routes.use('/pacienteEndereco', pacienteEnderecoRouter);
routes.use('/pacientePatologiaRisco', pacientePatologiaRiscoRouter);
routes.use('/patologia', patologiaRoutes);
routes.use('/procedimento', procedimentoRouter);
routes.use('/programa', programaRouter);
routes.use('/programaClinica', programaClinicaRouter);
routes.use('/prontuario', prontuarioRouter);
routes.use('/prontuarioExameFisico', prontuarioExameFisicoRouter);
routes.use('/prontuarioHabitoVida', prontuarioHabitoVidaRouter);
routes.use('/prontuarioHistoricoSaude', prontuarioHistoricoSaudeRouter);
routes.use('/prontuarioQueixaSaude', prontuarioQueixaSaudeRouter);
routes.use('/risco', riscoRouter);
routes.use('/solicitacao', solicitacaoRouter);
routes.use('/solicitacaoItem', solicitacaoItemRouter);
routes.use('/tipoAgendamento', tipoAgendamentoRouter);

export default routes;
